<?php

namespace App\Traits;

use App\Models\SMS;
use App\Models\SmsTransaction;
use App\Models\SmsBalance;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Log;

trait SMSServiceTrait
{
   /**
 * Send SMS and save response with balance tracking
 */
protected function sendSMSWithResponse(array $phones, string $message, $shopId, $customerId = null)
{
    $token = env('SMS_BEARER_TOKEN');

    // If no token, log and return (don't try to send)
    if (!$token) {
        Log::warning('SMS_BEARER_TOKEN not configured in .env');
        return [
            'success' => false,
            'error' => 'SMS service not configured'
        ];
    }

    // Prefer the shop's sender ID, fall back to env default. SMS providers
    // reject sends with no sender ID, so block early if neither is set.
    $shop = $shopId ? \App\Models\Shop::find($shopId) : null;
    $senderId = $shop?->sms_sender_id ?: env('SMS_SENDER_ID');
    if (!$senderId) {
        Log::warning('No SMS sender ID for shop', ['shop_id' => $shopId]);
        return [
            'success' => false,
            'error' => 'SMS sender ID not set. Ask your super admin to provision one.',
        ];
    }

    $response = Http::withHeaders([
        'Authorization' => 'Bearer ' . $token,
        'Content-Type'  => 'application/json',
    ])->post('https://app.mycsms.com/api/v3/sms/send', [
        'phone'     => $phones,
        'sender_id' => $senderId,
        'message'   => $message,
    ]);

    $result = null;

    if ($response->successful()) {
        $responseData = $response->json();
        $costInfo = $responseData['data']['cost_info'] ?? null;
        
        if ($costInfo && isset($phones[0])) {
            // Save SMS record - ID will be auto-generated by the model
            $sms = SMS::create([
                'customer_id' => $customerId,
                'recipient' => $phones[0],
                'message'   => $message,
                'type'      => 'single',
                'status'    => 'sent',
                'message_id' => $responseData['data']['results'][0]['message_id'] ?? null,
                'cost' => $costInfo['total_cost'] ?? null,
                'balance_before' => $costInfo['balance_before'] ?? null,
                'balance_after' => $costInfo['balance_after'] ?? null,
                'cost_info' => json_encode($costInfo),
            ]);

            // Save SMS transaction - ID will be auto-generated by the model
            SmsTransaction::create([
                'shop_id' => $shopId,
                'message_id' => $responseData['data']['results'][0]['message_id'] ?? null,
                'recipient' => $phones[0],
                'cost' => $costInfo['total_cost'] ?? 0,
                'recipient_count' => 1,
                'balance_before' => $costInfo['balance_before'] ?? 0,
                'balance_after' => $costInfo['balance_after'] ?? 0,
                'cost_info' => json_encode($costInfo),
                'type' => 'single',
            ]);

            // Update or create SMS balance
            $balance = SmsBalance::where('shop_id', $shopId)->first();
            if ($balance) {
                $balance->update([
                    'balance' => $costInfo['balance_after'],
                    'total_sent' => $balance->total_sent + 1,
                    'total_cost' => $balance->total_cost + ($costInfo['total_cost'] ?? 0),
                    'last_transaction_at' => now(),
                ]);
            } else {
                // ID will be auto-generated by the model
                SmsBalance::create([
                    'shop_id' => $shopId,
                    'balance' => $costInfo['balance_after'] ?? 0,
                    'total_sent' => 1,
                    'total_cost' => $costInfo['total_cost'] ?? 0,
                    'last_transaction_at' => now(),
                ]);
            }

            $result = [
                'success' => true,
                'message_id' => $responseData['data']['results'][0]['message_id'] ?? null,
                'cost_info' => $costInfo,
                'sms' => $sms
            ];
        }
    } else {
        Log::error('SMS API failed', [
            'status' => $response->status(),
            'body'   => $response->body(),
            'phones' => $phones,
        ]);
        
        $result = [
            'success' => false,
            'error' => $response->json()
        ];
    }

    return $result;
}

    /**
     * Format order items for SMS (list orders with costs)
     */
    protected function formatOrderItemsForSMS($items)
    {
        $formatted = "";
        foreach ($items as $index => $item) {
            $formatted .= ($index + 1) . ". " . $item['product_name'] . " x" . $item['quantity'] . " - GHS " . number_format($item['total'], 2) . "\n";
        }
        return $formatted;
    }

    /**
     * Send order confirmation SMS
     */
    protected function sendOrderConfirmationSMS($customer, $invoice)
    {
        if (!$customer || !$customer->phone) {
            return null;
        }

        $itemsList = $this->formatOrderItemsForSMS($invoice->items->toArray());
        
        $message = "🧾 ORDER CONFIRMATION - {$invoice->invoice_number}\n\n";
        $message .= "Thank you for your order!\n\n";
        $message .= "📋 ITEMS ORDERED:\n";
        $message .= $itemsList;
        $message .= "\n💰 SUBTOTAL: GHS " . number_format($invoice->subtotal, 2);
        $message .= "\n💵 TAX: GHS " . number_format($invoice->tax, 2);
        
        if ($invoice->discount > 0) {
            $message .= "\n🎉 DISCOUNT: -GHS " . number_format($invoice->discount, 2);
        }
        
        if ($invoice->shipping_cost > 0) {
            $message .= "\n🚚 SHIPPING: GHS " . number_format($invoice->shipping_cost, 2);
        }
        
        $message .= "\n💎 TOTAL: GHS " . number_format($invoice->total, 2);
        $message .= "\n💳 PAID: GHS " . number_format($invoice->amount_paid, 2);
        
        if ($invoice->amount_due > 0) {
            $message .= "\n⚠️ DUE: GHS " . number_format($invoice->amount_due, 2);
        }
        
        $message .= "\n\n📅 Date: " . $invoice->invoice_date->format('Y-m-d H:i');
        $message .= "\n📍 Order Type: " . ucfirst($invoice->order_type ?? 'standard');
        $message .= "\n\nThank you for shopping with us! 🙏";

        return $this->sendSMSWithResponse(
            [$customer->phone], 
            $message, 
            $invoice->shop_id, 
            $customer->id
        );
    }

    /**
     * Send payment confirmation SMS
     */
    protected function sendPaymentConfirmationSMS($customer, $invoice, $payment)
    {
        if (!$customer || !$customer->phone) {
            return null;
        }

        $message = "💰 PAYMENT CONFIRMATION\n\n";
        $message .= "Invoice #{$invoice->invoice_number}\n";
        $message .= "Amount Paid: GHS " . number_format($payment->amount, 2);
        $message .= "\nPayment Method: " . ucfirst($payment->payment_method);
        $message .= "\nPayment Date: " . $payment->payment_date->format('Y-m-d H:i');
        $message .= "\n\nTotal Paid to Date: GHS " . number_format($invoice->amount_paid, 2);
        
        if ($invoice->amount_due > 0) {
            $message .= "\nRemaining Balance: GHS " . number_format($invoice->amount_due, 2);
        } else {
            $message .= "\n✅ Order Fully Paid!";
        }
        
        $message .= "\n\nThank you for your payment! 🙏";

        return $this->sendSMSWithResponse(
            [$customer->phone], 
            $message, 
            $invoice->shop_id, 
            $customer->id
        );
    }
}